let questions = [
{ question: "Variable Life insurance policy owners may make withdrawals in terms of _______________.", options:[ "A. The number of units or fixed monetary amount through the cancellation of units.", "B. The number of units or fixed monetary amount through reduction of the life cover sum assured.", "C. The fixed monetary amount only through reduction of the life cover sum assured.", "D. The number of units through the cancellation of units."], answer: "A"},
{ question: "Which one of the following statement about the flexibility features of Variable Life Policies is FALSE?", options:[ "A. Policy owners may request for a partial withdrawal of the policy, and the withdrawal amount will be met by cashing the units at bid price.", "B. Policy owners can take loans against their Variable Life Policies up to the entire withdrawal value of their policies.", "C. Policy owners have the flexibility of switching from one fund to another provided it satisfies the company's switching criteria.", "D. Policy owners have the flexibility of increasing or decreasing their premiums for regular premiums variable life policies."], answer: "B"},
{ question: "The investment returns under Variable Life insurance policy<br/>I. Are not guaranteed<br/>II. Are assured<br/>III. Are linked to the performance of the investment fund management by the life company<br/>IV. Fluctuate according to the rise and fall of market prices", options:[ "A. I, II and III", "B. I, II and IV", "C. I, III and IV", "D. II, III and IV"], answer: "C"},
{ question: "Which of the following statements are TRUE?<br/>I. The policy value of Variable Life policies is determined by the offer price at the time of valuation.<br/>II. The policy value of Endowment policies is the cash value plus any accumulated dividends less any outstanding loans due at the time of surrender.<br/>III. The life company needs to maintain a separate account for Variable Life policies distinct from the general account.", options:[ "A. I, and II", "B. I,II and III", "C. I and III", "D. II and III"], answer: "D"},
{ question: "Which of the following statement is FALSE?", options:[ "A. Rebating is to offer a prospect a special inducement to purchase a policy.", "B. Twisting is a specific form of misrepresentation.", "C. Misrepresentation is a specific form of twisting.", "D. Switching is a facility allowing policy owners to switch to another Variable Life fund offered by the company."], answer: "C"},
{ question: "Which of the following statements about Variable Life Policies are TRUE?<br/>I. Offer price is used to determine the numbers of units to be cancelled from the account.<br/>II. The margin between the bid and offer price is used to cover the management cost of the policy.<br/>III. The policy value is calculated based on the bid price of units allocated into the policy.", options:[ "A. I, II and III", "B. I and II", "C. I and III", "D. II and III"], answer: "D"},
{ question: "What is the most suitable investment instrument for an investor who is interested in protecting his principal and receiving a steady stream of income?", options:[ "A. Equities", "B. Warrants", "C. Variable Life policies", "D. Fixed income securities"], answer: "D"},
{ question: "What are the disadvantages of investing in common shares?<br/>I. Dividends are paid not more than fixed rates.<br/>II. Investors are exposed to market and specific risks.<br/>III. Shares can become worthless if company becomes insolvent.", options:[ "A. I, II", "B. I,III", "C. II,III", "D. I,II and III"], answer: "C"},
{ question: "Which of the following statements about the differences between Variable Life policies and Endowment policies are FALSE?<br/>I. The policy values of Variable Life and Endowment policies directly reflect the performance of the fund of the life company.<br/>II. The premiums and benefits of the Endowment policies are described at inception of the policy whereas Variable Life policies are flexible as they are account driven.<br/>III. The benefits and risks Variable Life and Endowment policies directly accrue to the policy owners.", options:[ "A. I and II", "B. I,II and III", "C. I and III", "D. II and III"], answer: "C"},
{ question: "Which of the following statements about twisting is FALSE?", options:[ "A. Twisting is a special form of misrepresentation.", "B. It refers to an advisor inducing a policy owner to discontinue a policy with another company without disclosing the disadvantage of doing so. ", "C. It includes misleading or the incomplete comparison of policies.", "D. It refers to an advisor offering a prospect a special inducement to purchase a policy."], answer: "D"},
{ question: "Mr. Juan dela Cruz is currently earning P30,000/month. He is 35 years old and has a reasonable amount of savings. He has a moderate level of risk tolerance. What kind of policy would you recommend for him to buy?", options:[ "A. Participating Endowment", "B. Variable Life policies", "C. Participating Whole Life", "D. Annuities"], answer: "B"},
{ question: "What are the benefits available when investing in Variable Life funds?<br/>I. The Variable Life funds offer policy owners an access to a pooled of diversified portfolios.<br/>II. The Variable Life policy owner can vary his premiums payments, take premium holidays, add single premium top-ups and change the level of sum assured easily.<br/>III. The Variable Life policy owner can have access to a pool of qualified and trained professional fund managers.", options:[ "A. I and II", "B. I and III", "C. I, II and III", "D. II and III"], answer: "C"},
{ question: "Rank the following in terms of their liquidity, from the least liquid to the most liquid.<br/>I. Short Term Securities<br/>II. Property<br/>III. Cash<br/>IV. Equities", options:[ "A. IV,II,III,I", "B. III,I,IV,II", "C. II,I,IV,III", "D. II,IV,I II"], answer: "C"},
{ question: "A UNIT TRUST is __________________________________________________", options:[ "A. Established by a trust deed which enables a trustee to hold the pool of money and assets in trust on behalf of the investor.", "B. A closed-end fund and does not have to dispose of its assets if large number of investors sell their shares", "C. One whereby an investor buys units in the trust itself and not from the shares in the company.", "D. An organization registered under the Security and Exchange Commission (SEC) which usually invests in a wide range of equities and other investments."], answer: "A"},
{ question: "Under Variable Life Insurance policies ________________<br/>I. There is no guaranteed minimum sum for the purpose of declaring dividends.<br/>II. There is no guaranteed minimum sum assured as a level of life insurance protection.<br/>III. Each of the policy owner's premiums will be used to purchase units, the number of which is dependent on the selling price of each unit.<br/>IV. Purchase of units can only be made from the Variable Life Fund itself, which will then create new units and add the investment monies to the value of the fund. ", options:[ "A. I and IV", "B. II and IV", "C. III and IV", "D. II and III"], answer: "C"},
{ question: "The benefits of investing in Variable Life fund include:<br/>I. Policy Owners have access to a pooled and diversified portfolio of investment.<br/>II. Policy Owner can easily change the level of premium payments as the product design of Variable Life insurance policies have clear structures which cater separately for investment and insurance protection.<br/>III. Policy Owners can gain access to Variable Life funds managed by professional investment managers with proven track records.<br/>IV. Policy Owners can buy a Variable Life insurance policy only with a high initial investment", options:[ "A. I, II, and IV", "B. I, III, and IV", "C. I, II, and III", "D. II,III and IV"], answer: "C"},
{ question: "Which of the following BEST describes the policy benefits of Variable Life policies?", options:[ "A. The policy benefits are payable only for the death or disability.", "B. The policy benefits will depend on the long-term performance of the life company.", "C. The policy benefits are directly linked to the investment performance of the underlying assets.", "D. The policy benefits are guaranteed."], answer: "C"},
{ question: "Why is it important that the customer must understand the sales proposal in full?", options:[ "A. Because the insurer does not guarantee any return", "B. Because the impact of changes in investment condition on variable life policy borne solely by the customer", "C. Because the agent may give the wrong recommendations", "D. Because the policyholders expects higher returns"], answer: "B"},
{ question: "Which of the following statements about rebating are TRUE?<br/>I. Rebating is prohibited under the Insurance Code.<br/>II. Rebating deals with offering the prospect a special inducement to purchase a policy.<br/>III. Rebating will enhance the sales performance and uphold the prestige of an advisor.", options:[ "A. I and II", "B. I and III", "C. II and III", "D. None of the above"], answer: "A"},
{ question: "Which one of the following statements is FALSE?", options:[ "A. Variable Life insurance policies offer investors policies with values and are indirectly linked to the investment performance of the life company.", "B. A life company will carry out a valuation of its funds yearly and any surplus may be allocated to participating policy owners as cash dividends.", "C. Both Whole Life and Endowment policies can be used as an investment media with benefits that become payable at a future date.", "D. The investment element of Variable Life policies varies according to the underlying assets of portfolio."], answer: "A"},
{ question: "Which one of the following statements about the option to top-up under Variable Life insurance products is FALSE?", options:[ "A. Policy owners may buy additional units of the Variable Life fund and these units will be allocated to new Variable Life insurance policies.", "B. Further premiums at the time of top-ups will be used in full, after deducting charges for topups, to purchase additional units of the Variable Life funds.", "C. To top-up policy, the policy owner pays further single premium at the time of top-up.", "D. Policy owners are normally allowed to top-up their policies at any time, subject to a minimum amount."], answer: "A"},
{ question: "The characteristics of a Variable Life insurance policy include __________________.<br/>I. Its withdrawal value and protection benefits are determined by the investment performance of the underlying assets.<br/>II. Its protection costs are generally met by implicit charges.<br/>III. Its commission and company expenses are met by a variety of implicit charges with normally 6 months' notice given by the life companies prior to any change.<br/>IV. Its withdrawal value is normally the value of units allocated to the policy owner calculated at the bid price.", options:[ "A. I,II and III", "B. II,III and IV", "C. I,II and IV", "D. I,III and IV"], answer: "D"},
{ question: "Which of the following statements about single premium Variable Life policies are TRUE?<br/>I. There is no fixed term in a single premium Variable Life policy and therefore, they are technically Whole Life insurance.<br/>II. Top-ups single premium injections are allowed in these plans.<br/>III. Policy Owners have the flexibility of varying the level cover.", options:[ "A. I, II and III", "B. II and III", "C. I and II", "D. I and III"], answer: "A"},
{ question: "Investing in bonds offer the following advantages EXCEPT:", options:[ "A. It offers protection to the principal and guarantees a steady stream of income.", "B. It is place of temporary refuge when the investor foresees that the market outlook is uncertain.", "C. It allows the investor a chance for capital preservations.", "D. It enables the investors an opportunity for capital appreciation."], answer: "D"},
{ question: "Which of the following statements about Variable Life policies are TRUE?<br/>I. The withdrawal value is not guaranteed.<br/>II. The volatility of the returns depends on the investment strategy of the fund.<br/>III. The Variable Life policy owner has direct control over the investment decisions of the Variable Life fund.", options:[ "A. I,II and III", "B. I and II", "C. I and III", "D. II and III"], answer: "B"},
{ question: "A Single Premium Variable Life insurance policy:", options:[ "A. Must be issued with a minimum death benefit", "B. Must be issued with a maximum withdrawal value", "C. Has no death benefit", "D. Has no withdrawal value"], answer: "A"},
{ question: "Which of the following statements about the characteristics of Variable Life policies are TRUE?<br/>I. Variable Life policies generally have larger exposure to equity investments than with participating and other traditional policies.<br/>II. The protection costs are generally met by implicit charges, which vary with age and level of cover.<br/>III. Commissions and company expenses are met by a variety of explicit charges, some of which are variable.", options:[ "A. I,II and III", "B. I and II", "C. II and III", "D. I and III"], answer: "D"},
{ question: "Which of the following statements about the benefits in Variable Life fund is FALSE?", options:[ "A. The fund provides a highly diversified portfolio, thus, lowering the risk of investment.", "B. The fund ensures definite high yield for an investor since it is managed by professionals who are well-versed in the management of risks of investment portfolios.", "C. The fund relieves the investor from the hassles of administering his/her investment.", "D. The fund enables small investors to participate in a pool of diversified portfolios in which he/she with low investment capital is likely to have acceded to."], answer: "B"},
{ question: "The Flexibility benefits of investing in Variable Life funds include_____________.<br/>I. The policy owner can easily change the level of sum assured and switch their investment between funds.<br/>II. Policy owners can easily take premium holidays and add single premium to top-ups<br/>III. Variable Life insurance products have simple product design with a clear structure, which cater separately for investment and insurance protection.<br/>IV. Policy owners can easily change the level of their premium payment.", options:[ "A. All of the above", "B. I,II and III", "C. I,II and IV", "D. I,III and IV"], answer: "A"},
{ question: "The Fundamental differences between traditional participating life insurance policies and Variable Life insurance policies include________________.<br/>I. Variable Life insurance policies are less likely to offer more choices in terms of the type of investment funds.<br/>II. The investment elements of Variable Life insurance policies are made known to the policy owner at the outset and are invested in a separately identifiable fund which is made up of units of investment.<br/>III. Variable Life insurance policies offer the potential for higher returns.<br/>IV. Traditional participating policies aim to produce a steady return by smoothing out market fluctuation. ", options:[ "A. I,III and IV", "B. II,III and IV", "C. I,II and IV", "D. I,III and IV"], answer: "B"},
{ question: "The switching facility under Variable Life insurance policies is very useful ________________.", options:[ "A. For the purpose of profit planning by the life policies", "B. For the purpose of assets planning by the trustee.", "C. For the purpose of sales planning by the fund managers.", "D. For the purpose of financial planning by the policy owners."], answer: "D"},
{ question: "Which of the following statements about surrender value under Traditional participating life insurance products is TRUE?", options:[ "A. Cash Value is paid when a yearly renewable term insurance policy is surrendered.", "B. When a participating insurance policy is surrendered, the surrender value is calculated by multiplying the bid price with the number of units.", "C. The amount of surrender value is usually higher than the amount under non-participating policies and it varies with the age of the assured, being lower at older ages.", "D. In the case of participating policies, the net cash surrender value includes the surrender value of the paid-up addition to the date of surrender."], answer: "D"},
{ question: "Which of the following statements about the risk of investing in Variable Life funds is TRUE?", options:[ "A. Policy owners who are risk averse should buy Variable Life Insurance policies with high equity investment.", "B. Investments in Variable Life funds which are fully invested in units of equity bonds are not suitable for policy owners who can tolerate the risks of short term fluctuation in their cash value.", "C. Policy owners who invest in Variable Life funds with high equity investment face greater risk but can expect to achieve higher return than the Traditional Life insurance product over the long term.", "D. Policy owners who are risk averse should not purchase life insurance policies with high protection and guaranteed cash and maturity values."], answer: "C"},
{ question: "What would be the withdrawal value after a year?<br/>Offer Price = P16.00<br/>Bid-offer spread = 4.5%<br/>Number of Units bought = 25,000<br/>Policy Fee = P1,800<br/>Admin and Mortality Charge = P8,750<br/>Top-up Fee = P700<br/>Admin for Top-up = P2,000<br/>Sum assured is 190% of single premium or the value of the units, whichever is higher.<br/>Assumptions:<br/>1. Charges and Fees are deducted after the single premium has been invested into the account.<br/>2. The growth rate of the unit price and the bid-offer spread is maintained at 8% and 4.5% respectively.", options:[ "A. Ps. 432,000.00", "B. Ps. 420,069.00", "C. Ps. 401,107.58", "D. Ps. 412,500.00 "], answer: "C"},
{ question: "The protection costs under a Variable Life insurance policy _________________.<br/>I. Are met by flat initial charges for regular premium plans.<br/>II. Are generally covered by the cancellation of units in the fund.<br/>III. Are generally met by explicit charges stipulated openly in the policy terms.<br/>IV. Vary with age of policy owner and level of cover.", options:[ "A. I,II and III", "B. I,II and IV", "C. I,III and IV", "D. II,III and IV"], answer: "D"},
{ question: "Which one of the following statements about diversification in Portfolio management is FALSE?", options:[ "A. A Diversified portfolio provides greater security to an investor having to sacrifice the return for the portfolio.", "B. Diversification can completely eliminate the risk of investing in stocks in a portfolio.", "C. Diversification can involve purchasing different types of stocks and investing in stocks of different countries.", "D. Diversification helps to spread the portfolio risk by investing in different categories of investment in a portfolio."], answer: "B"},
{ question: "What are the advantages of investing in preferred shares?<br/>I. It gives shareholders the right to a fixed dividend.<br/>II. Has the priority over company assets during dissolution.<br/>III. They enjoy the benefits of capital appreciation.", options:[ "A. I,II and III", "B. I and II", "C. I and III", "D. II and III"], answer: "A"},
{ question: "With traditional participating life insurance products, the allocations to policy owners in the form of dividends:<br/>I. Are not directly linked to the investments performance of the life company.<br/>II. Have already been smoothened by the life company.<br/>III. Do not have the highs and lows of investment returns as in good investment years of the life company.<br/>IV. Are not fixed at the inception of the policy, but are greatly dependent on the investment performance of the life company.", options:[ "A. I,II and III", "B. I,II and IV", "C. I,III and IV", "D. II,III and IV"], answer: "D"},
{ question: "The objective of satisfying the customers' need profitability can be achieved by an advisor through:<br/>I. The giving of freebies to the customers.<br/>II. Extensive investment training by the company.<br/>III. The use of sales plan, where sales goals, strategies and objectives are coordinated with<br/>market analysis, segmentation and targeting.<br/>IV. The giving of monetary assistance and discount to customers.", options:[ "A. I and III", "B. II and III", "C. I,II and IV", "D. II,III and IV"], answer: "B"},
{ question: "Which of the following statements about cash is TRUE?", options:[ "A. It has high yield potential.", "B. The amount invested in cash depends on the size of the cash flow requirement.", "C. Investment in cash increases when there is a bull run in the stock market.", "D. Investment in cash decreases interest rates rise."], answer: "B"},
{ question: "Under a Regular Premium Variable Whole Life insurance plan ________________________.<br/>I. Premium top-ups and holidays, subject to the life company's administrative rules are usually allowed.<br/>II. Life protection is the main objective of the plan with investment as a nominal purpose.<br/>III. Withdrawals after the payment of a few years' premium are usually allowed.<br/>IV. A single premium contribution is made to the policy which uses the premium to purchase units in a Variable Life fund and to provide a certain level of life cover.", options:[ "A. II, III and IV", "B. I,III and IV", "C. I,II and IV", "D. I,II and III"], answer: "D"},
{ question: "Which of the following statements about investment objective is FALSE?", options:[ "A. People invest money in fixed deposits to produce high and guaranteed returns.", "B. People invest money to enhance a comfortable standard of living", "C. People invest money to provide funds for the higher education of their children.", "D. Investment in commodities has no regular income."], answer: "A"},
{ question: "Which of the following are the main characteristics of variable life policies?<br/>I. The policies can be used for investments, as a source of regular savings and protection.<br/>II. The withdrawal values and protection benefits are determined by the investment performance of the underlying assets.<br/>III. The net cash values of the policies are the gross withdrawal values shown in the policy which includes cash dividends up to the date of surrender, less any indebtedness, including interest.", options:[ "A. II", "B. I", "C. I,II and III", "D. I and II"], answer: "D"},
{ question: "Risk can be classified into two particular categories in relation to investment. They include ______:<br/>I. The risk of not losing some or all of a person's initial investment.<br/>II. The risk of rate of return on the investment not matching up to the individual's expectation.<br/>III. The risk of rate of return on the investment matching up to the individual's expectation.<br/>IV. The risk of losing some or all of a person's initial investment.", options:[ "A. I and III", "B. I and II", "C. III and IV", "D. II and IV"], answer: "D"},
{ question: "The duties of the trustees of a unit do not include:", options:[ "A. Managing the portfolio of investment and administering the buying and selling of shares in the unit trust itself.", "B. Ensuring that the fund manager adhere to the provision of the trusts deeds", "C. Acting generally to protect the unit-holders.", "D. Holding the pool of money and assets in trust in behalf of the investors."], answer: "A"},
{ question: "The policy fee payable by a Variable Life insurance policy owner is to cover _______:", options:[ "A. The handling charges by professional investment managers.", "B. The pric e for each unit bought under the Variable Life insurance policy.", "C. The mortality costs of the Variable Life insurance policy.", "D. The administrative expenses of setting up the Variable Life insurance policy."], answer: "D"},
{ question: "The selling price under a Variable Life insurance policy is:", options:[ "A. The price at which units the policy is bought back by the life company.", "B. The price at which units under the policy are offered for the sale by the life company.", "C. Also known as the bid price.", "D. A fixed amount throughout."], answer: "B"},
{ question: "In the risk-return profile of cash funds, bond funds, balanced funds, managed funds, and equity funds, a risk-return graph will show that _______________.<br/>I. Higher return normally comes with lower risk.<br/>II. Higher return normally comes with higher risk.<br/>III. At the top end of the graph are equity funds.<br/>IV. The relatively risk-less cash funds sit at the bottom end of the graph.", options:[ "A. I, II and III", "B. II, III and IV", "C. I, II and IV", "D. I, III and IV"], answer: "B"},
{ question: "Diversification in investment involves _______________________.", options:[ "A. Putting all the funds under management into one category of investment.", "B. Spreading the risks of investment by not putting the fund into several categories of investment", "C. Reducing the risks of investment by putting one fund under management into several categories of investment.", "D. Reducing the risks of investment by putting all one' eggs in one basket."], answer: "C"},
{ question: "Variable Life funds can be invested in any financial instruments including cash funds, bond funds, equity funds, property funds, specialized funds and diversified funds. Equity funds ____________:", options:[ "A. Invest in shares of stocks and the magnitude of the change in unit prices will only depend on the quantity of the equities held.", "B. Invest in shares of stocks and during market recession, such assets are usually the last to depreciate.", "C. Invest in share of stocks which are inherently of lower risk in nature and the prices of stocks are stable. ", "D. Invest in shares of stocks and an investor who buys such assets usually aims for capital appreciation. "], answer: "D"},
{ question: "People generally invest their money to provide:<br/>I. An improvement in their financial position<br/>II. A less comfortable standard of living<br/>III. Retirement income<br/>IV. Funds for paying necessary expenses and taxes when the person dies", options: ["A. I, II and III", "B. I, III and IV", "C. I, II, and IV", "D. II, III and IV"], answer: "B"},
{ question: "Which of the following funds is comprised of a higher proportion of equity and a lower proportion of fixed-income instruments?", options: ["A. Bond Funds", "B. Cash Funds", "C. Managed Funds", "D. Mixed Funds"], answer: "C"},
{ question: "Which of the following are the main characteristics of Variable Life Insurance policies?<br/>I. The policies can be used for investments, as a source of regular savings and protection.<br/>II. The withdrawal and protection benefits are determined by the investment performance of the underlying assets.<br/>III. The net withdrawal values of the policies are the gross withdrawal values shown in the policy which includes cash dividends up to the date of surrender, less all indebtedness, including interests.", options: ["A. I only", "B. II only", "C. I and II only", "D. I, II and III"], answer: "C"},
{ question: "Which of the following statements are FALSE?<br/>I. The Policy owners may request a partial withdrawal of the policy and the amount will be met by cashing the units at the offer price<br/>II. The structure of charges and the investment content of a Variable Life Policy are specified in the policy document and the policy statement.<br/>III. Some Variable Life Policies grant loans to policy owners which is limited to a percentage of the cash value.<br/>IV. Commissions and office expenses are met by a variety of implicit charges, some of which are variable.", options: ["A. I and II only", "B. I and III only", "C. II and III only", "D. All of the above"], answer: "B"},
{ question: "Which of the following statements about the feature of Regular Premium Variable Life Policy are TRUE?<br/>I. Top-ups are usually allowed.<br/>II. The level of cover can be varied.<br/>III. Premium holidays are usually allowed.", options: ["A. I and II only", "B. I and III only", "C. II and III only", "D. I, II and III"], answer: "D"},
{ question: "Which one of the following statements is NOT TRUE about the benefits of investing in a Variable Life insurance policy?", options: ["A. The fund provides a highly diversified portfolio, thus, lowering the risk of investment.", "B. The fund relieves the investor from the hassles of administering his/her investment.", "C. The fund ensures definite high yield for an investor since it is managed by professionals who are well-versed in the management of risk of an investment portfolio.", "D. The fund enables small investors to participate in a pool of diversified portfolios in which he/she is unlikely to have access to with low investment capital."], answer: "C"},
{ question: "Which of the following statements describes the difference between Variable Life insurance products and traditional participating products?<br/>I. Variable Life insurance products allow policy owners to change the premium payments but traditional participating life products do not.<br/>II. Variable life insurance products can take the form of Whole Life or Endowment policies but Traditional Life Policies cannot.<br/>III. Variable Life Insurance products allow the policy owners to pay future single premiums from time to time to add more units to his accounts but Traditional Life participating products do not.", options: ["A. I only", "B. I and III only", "C. II and III only", "D. I, II and III"], answer: "B"},
{ question: "Which of the following are some of the flexibility features of Variable Life insurance policies?<br/>I. Partial withdrawal<br/>II. Variation in sum assured<br/>III. Guaranteed withdrawal values", options: ["A. II only", "B. III only", "C. I and II only", "D. I, II and III"], answer: "C"},
{ question: "Which of the following statements about Single Premium Variable Life policies are TRUE?<br/>I. There is no fixed term in a single premium Variable Life policy and therefore, it is technically Whole Life insurance.<br/>II. Top-ups or single premium injections are allowed.<br/>III. Policy Owners have the flexibility of varying the life coverage.", options: ["A. I and II", "B. I and III", "C. II and III", "D. I, II and III"], answer: "C"},
{ question: "The benefits of investing in Variable Life fund include:<br/>I. Policy Owners have access to a pooled and diversified portfolio of investment.<br/>II. The Policy Owner can easily change the level of premium payments as the product design of Variable Life insurance policies have clear structures which cater separately for investment and insurance protection.<br/>III. Policy Owners can gain access to Variable Life funds managed by professional investment managers.<br/>IV. The Policy Owner is relieved of the day to day administration of his investment", options: ["A. I, II, and III", "B. I, II, and IV", "C. I, III, and IV", "D. All of the above"], answer: "D"},
{ question: "The flexibility benefits of investing in Variable Life funds include:<br/>I. Policy Owners can easily change the level of sum insured and switch their investments between funds.<br/>II. Policy owners can easily take premium holidays and add single premium top-ups.<br/>III. Variable Life insurance products have simple product design with a clear structure which caters separately for investment and insurance protection.<br/>IV. Policy Owner can easily change the level of their premium payment.", options: ["A. I, II, and III", "B. I, II, and IV", "C. I, III, and IV", "D. I,II,III, and IV"], answer: "B"},
{ question: "Which of the following statements describe the difference between Variable Life products and traditional participating life products?<br/>I. Variable Life products allow policy owners to pay top-up premiums from time to time to buy more units for his account unlike traditional participating life policies.<br/>II. Variable Life products allow policy owners to take premium holiday unlike traditional participating life products.<br/>III. Variable Life products can take the form of Whole Life or Endowment policies unlike traditional participating life products.", options: ["A. I", "B. I and II", "C. I and III", "D. I,II, and III"], answer: "B"},
{ question: "Your client is a 35 year-old male, earning P35,000 a month, has savings, and with a moderate risk tolerance. What product would you recommend?", options: ["A. Participating Whole Life", "B. Endowment", "C. Term", "D. Variable Life"], answer: "D"},
{ question: "In a Unit Trust Investment, the duties of a Trustee include all of these EXCEPT:", options: ["A. Selects and manages the investments of the Trust.", "B. Holds the pool of money and assets in trust on behalf of the investors", "C. Ensures that the fund managers adhere to the provisions of the trust deed.", "D. Protects the interests of unit holders."], answer: "A"},
{ question: "To the policy owners, administration benefits under Variable Life include:", options: ["A. Engaging independent professional fund managers personally to manage the complicated transaction.", "B. Constructing their own diversified portfolio.", "C. Keeping track of their investment through the statements provided regularly by the insurance company.", "D. Exercising investment expertise by selecting funds that will give higher returns."], answer: "C"},
{ question: "Which statement best describes Variable Life?", options: ["A. Fixed premium with returns that will not vary.", "B. Fixed premium with returns that will vary.", "C. Flexible premium with returns that will not vary.", "D. Flexible premium with returns that will vary."], answer: "D"},
{ question: "With traditional participating life insurance products, the allocations to policy owners of dividends:<br/>I. Are not directly linked to the investments of the life company.<br/>II. Are smoothened<br/>III. Do not have the highs and lows of investment returns in good times.<br/>IV. Are not fixed. ", options: ["A. I and II", "B. I, II and III", "C. I, II, IV", "D. II and IV"], answer: "D"},
{ question: "Offer Price = P16 Administrative and Mortality Charges = P8,750<br/>Bid-Offer Spread = 4.5% Top-up Fee = P700<br/>Units = 25,000 Administrative Top-up Fee = P2,000<br/>Policy Fee = P1,800<br/>Presuming all charges are deducted by canceling units and that the bid price increases by 8%,<br/>what is the withdrawal value after a year?", options: ["A. 432,000", "B. 420,069.02", "C. 401,107.58", "D. 412,500"], answer: "C"},
{ question: "Which statements are FALSE regarding the difference between Endowment policies and Variable Life policies?<br/>I. The benefits and risks of Endowment and Variable Life policies directly accrue to the Policy Owners.<br/>II. The premiums and benefits of Endowment policies are stated at its inception while those of Variable Life policies are flexible as they are account driven.<br/>III. Their policy values directly reflect the performance of the fund of the life company.", options: ["A. I and II", "B. I and III", "C. II and III", "D. I, II and III"], answer: "B"},
{ question: "Which statement about cash is TRUE?", options: ["A. Investment in cash increases when there is a bull run in the stock market.", "B. Investment in cash decreases when there is a rise in interest rates.", "C. Amount invested in cash is dependent on the size of the cash flow requirement.", "D. Its yield potential is high."], answer: "C"},
{ question: "These statements are true EXCEPT", options: ["A. No regular income may be gained from investing in commodities.", "B. Investing in fixed deposits gives high guaranteed returns.", "C. People invest money to enhance a comfortable standard of living.", "D. People invest money to provide funds for the higher education of their children"], answer: "B"},
{ question: "For Variable Life policy, the definition of selling price is:", options: ["A. The price at which units under the policy is offered for sale by the life insurance company.", "B. It is also known as the bid price.", "C. The price at which units under the policy are bought back by the life insurance company.", "D. It is a fixed amount throughout the life of the policy."], answer: "A"},
{ question: "Which statement regarding the risk of investment in Variable Life is TRUE?", options: ["A. Policy Owners who are risk averse should not purchase a life insurance policy with high protection and guaranteed cash and maturity values.", "B. Investments in Variable Life funds which are fully invested in units of equity funds are not suitable for Policy Owners who can tolerate the risks of short term fluctuation in their cash value.", "C. Policy Owners who invest in Variable Life funds with high equity investment face greater risk but can expect to achieve higher return than Traditional Life insurance policies with high equity investment.", "D. Policy Owners who are risk averse should buy Variable Life policies with high equity investment."], answer: "C"},
{ question: "The statements below are true about the top-up option of a Variable Life insurance product EXCEPT:", options: ["A. The Policy Owner pays further single premium to make a top-up.", "B. Normally, Policy Owners are allowed to make a top-up on their policies at any time subject to a minimum amount.", "C. Policy Owners may buy additional units of Variable Life fund and these units will be allocated to new Variable Life insurance policies.", "D. Further premiums at the time of top-up will be used in full after deducting charges to purchase additional units of the Variable Life funds."], answer: "C"},
{ question: "If the current offer price = P2.50 and the bid-offer spread = 4% what is the bid price?", options: ["A. P2.40", "B. P2.50", "C. P2.60", "D. P2.70"], answer: "A"},
{ question: "Which of the following statements are FALSE?<br/>I. The bid-offer is used to provide a death benefit for the Variable Life insurance policy.<br/>II. The bid price is always higher than the offer price.<br/>III. The bid-offer spread is usually about 5%.<br/>IV. There are two types of death benefits under the Variable Life insurance product. They may offer either/or both types depending on its product design and on the discretion of the policy owner.", options: ["A. I and II", "B. II and III", "C. II and IV", "D. None of the above"], answer: "A"},
{ question: "Which is NOT a characteristic of a Variable Life policy?", options: ["A. It is used solely for investment purposes.", "B. The commission and office expenses are met by explicit charges.", "C. It has generally, though not necessarily, more exposure to equity investments.", "D. Its cash value is usually the value of units allocated to the policy calculated at the prevailing bid price."], answer: "B"},
{ question: "Which of the following statements about investment returns under a Variable Life insurance policy is NOT TRUE?", options: ["A. It is assured", "B. It is not guaranteed", "C. It fluctuates based on the rise and fall of market prices", "D. It is linked to the performance of the investment fund managed by the life insurance company"], answer: "D"},
{ question: "Which statements are FALSE regarding the difference between Endowment policies and Variable Life policies?<br/>I. The benefits and risks of Endowment and Variable Life policies directly accrue to the Policy Owners.<br/>II. The premiums and benefits of Endowment policies are stated at its inception while those of Variable Life policies are flexible as they are account driven.<br/>III. Their policy values directly reflect the performance of the fund of the life company.", options: ["A. I and II", "B. I and III", "C. II and III", "D. I, II and III"], answer: "B"},
{ question: "What are the ADVANTAGES of investing in preferred shares?<br/>I. It has priority on company assets during dissolution<br/>II. It has a benefit of capital appreciation<br/>III. The shareholder has the right to a fixed dividend", options: ["A. I and II", "B. I and III", "C. II and III", "D. I, II and III"], answer: "A"},
{ question: "Which of the following information is NOT required to be disclosed to policy owners of Variable Life policies?", options: ["A. The basis and frequency for valuing the assets ", "B. The number and value of units held at the beginning of the period, bought and sold during the period, and held at the end of the period.", "C. The net withdrawal as of the statement date", "D. The premiums received and charges levied during the period."], answer: "A"},
{ question: "The investment returns under Variable Life insurance policy<br/>I. Are not guaranteed<br/>II. Are insured<br/>III. Are linked to the performance of the investment fund managed by the life office<br/>IV. Fluctuate according to the rise and fall of market prices", options: ["A. I, II and III", "B. I, II and IV", "C. I, III and IV", "D. II, III and IV"], answer: "C"},
{ question: "Which of the following are fixed income securities?<br/>I. Corporate Stocks<br/>II. Government Bonds<br/>III. Preferred Shares<br/>IV. Money Market Instruments<br/>V. Properties", options: ["A. I, II, III and IV only", "B. I and III only", "C. I, III and V only", "D. All of the above"], answer: "A"},
{ question: "Which of the following investment options entitles the holder ownership and share of profits in the form of dividends appreciation?", options: ["A. Cash", "B. Bonds", "C. Futures", "D. Ordinary Shares"], answer: "D"},
{ question: "Which of the following statements are FALSE?<br/>I. Higher Capital gain is normally associated with lower risk<br/>II. One way to lower risk in investment is to diversify<br/>III. One method of measuring risk is to determine the average return and its standard deviation from future data<br/>IV. Diversification can be achieved by investing in different countries and/or types of assets<br/>V. An investor can always choose an investment that is risk free", options: ["A. I, II and III only", "B. II, III and IV only", "C. I, III and V only", "D. All of the above"], answer: "C"},
{ question: "The difference between the offer price and the bid price is?", options: ["A. Bid price spread", "B. Offer price spread", "C. Bid-offer spread", "D. None of the above"], answer: "C"},
{ question: "Which of the following information must NOT be conveyed to the client in the sale of Variable Life insurance policies", options: ["A. Guaranteed interest rate", "B. Time horizon of the product", "C. Benefits illustrations using 10% as the gross", "D. Rate of return"], answer: "A"},
{ question: "Term Insurance _______________", options: ["A. Provides for payment of the sum insured when the life insured survives a specific period.", "B. Provides protection for a specific period and has no saving element.", "C. Is the most complex and expensive of all life insurance products.", "D. Provide for surrender of cash values on early termination of the insurance."], answer: "B"},
{ question: "What are the disadvantage of investing in cash and deposits?<br/>I. It is the safest type of investment.<br/>II. They provide the lowest return.<br/>III. There is reinvestment risk", options: ["A. I only", "B. II only", "C. II and III only", "D. I, II and III"], answer: "C"},
{ question: "Which of the following are types of corporate stocks?<br/>I. Debenture stocks<br/>II. Government stocks<br/>III. Loan stocks<br/>IV. Money Market Instruments<br/>V. Convertible Stocks", options: ["A. I, II and III only", "B. I, II, III and IV only", "C. I, III and V only", "D. All of the above"], answer: "C"},
{ question: "Factors to consider in buying Properties:<br/>I. Quality of land<br/>II. The location of land<br/>III. The value of building of land<br/>IV. The investment<br/>V. Place of work", options: ["A. I, II and III only", "B. II, III and IV only", "C. I, III and V only", "D. All of the above"], answer: "A"},
{ question: "What are the basic types of real estate investments?<br/>I. Rural Property<br/>II. Domestic Property<br/>III. Agricultural Property<br/>IV. Commercial/Industrial Property<br/>V. Foreign Property", options: ["A. I, II and III only", "B. II, III and IV only", "C. I, III and V only", "D. All of the above"], answer: "B"},
{ question: "The amount of risk a person can take depends on:<br/>I. Age<br/>II. Investment objective<br/>III. Financial conditions<br/>IV. Personality", options: ["A. I and II only", "B. II, III and IV only", "C. I, II and III only", "D. All of the above"], answer: "D"},
{ question: "All of these are mandatory provisions in a Variable Life policy contract EXCEPT:", options: ["A. Incontestability Provision", "B. The Entire Insurance Contract Provision", "C. Misstatement of Age or Sex Provision", "D. None of the above"], answer: "D"},
{ question: "What is the “Net Amount at Risk”?", options: ["A. The minimum death benefit", "B. The excess between the minimum death benefit and the value of the policy owner’s separate variable account", "C. The sum insured", "D. The difference between the minimum death benefit and the sum assured"], answer: "B"},
{ question: "If a policy owner fails to pay premium on time and there are no withdrawal values in the account, the policy will:", options: ["A. Continue in full force for a period of grace.", "B. Terminate immediately on the day premium is due.", "C. Continue at reduced sum assured.", "D. Continue at the same sum assured for the same basic benefits."], answer: "B"},
{ question: "If a policy owner returns the Variable Life insurance contract within the cooling-off period, he will receive:", options: ["A. A refund equal to the market value of the units plus initial charges.", "B. All premiums paid.", "C. A refund equal to the market value of the units only", "D. Nothing."], answer: "A"},
{ question: "Which of the following statements about investment objectives is FALSE?", options: ["A. People invest money to enhance a comfortable standard living.", "B. People invest money to provide funds for the higher education of their children.", "C. Investment and commodities produce no regular income.", "D. People invest money in equities to produce high and guaranteed income."], answer: "D"},
{ question: "The disadvantages of fixed income securities include:<br/>I. The coupon rate is fixed and cannot respond to inflation.<br/>II. The investors are exposed to market specific risks.<br/>III. Fluctuations in bond prices may lead to capital losses.", options: ["A. II and III only", "B. I and II only", "C. I, II and III", "D. I and III only"], answer: "B"},
{ question: "Which of the following statements about rebating are TRUE?<br/>I. Rebating is prohibited under the Insurance Code.<br/>II. Rebating deals with offering the prospect a special inducement to purchase a policy.<br/>III. Rebating will enhance the sales performance and uphold the prestige of an advisor.", options: [ "A. I and II", "B. I and III", "C. II and III"], answer: "A"},
];

function getRandomQuestions(qList, num) {
    let shuffled = qList.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, num);
}

let selectedQuestions = getRandomQuestions(questions, 122);
let questionsDiv = document.getElementById('questions');

selectedQuestions.forEach((q, index) => {
    let questionHTML = `<p>${index + 1}. ${q.question}</p>`;
    q.options.forEach(option => {
        questionHTML += `<label><input type="radio" name="q${index}" value="${option[0]}"> ${option}</label><br>`;
    });
    questionsDiv.innerHTML += questionHTML;
});

// let timeLeft = 2700; // 45 minutes in seconds
let timeLeft = 1800; // 30 minutes in seconds
// let timeLeft = 600; // 10 minutes in seconds
// let timeLeft = 1200; // 20 minutes in seconds
// let timeLeft = 10; // 60 seconds
function updateTimer() {
    let minutes = Math.floor(timeLeft / 60);
    let seconds = timeLeft % 60;
    document.getElementById('time').textContent = `${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;
    if (timeLeft > 0) {
        timeLeft--;
        setTimeout(updateTimer, 1000);
    } else {
        document.getElementById("submitButton").click();
    }
}

updateTimer();

document.getElementById('quizForm').addEventListener('submit', function(event) {
    event.preventDefault();
    let score = 0;
    let formData = new FormData(event.target);
    let results = [];

    selectedQuestions.forEach((q, index) => {
        let userAnswer = formData.get(`q${index}`);
        let correctAnswer = q.answer;
        if (userAnswer === correctAnswer) {
            score++;
        } else {
            results.push({
                question: q.question,
                userAnswer: userAnswer || "No Answer",
                correctAnswer: correctAnswer,
                options: q.options
            });
        }
    });

    localStorage.setItem('quizScore', score);
    localStorage.setItem('quizResults', JSON.stringify(results));
    window.location.href = 'full-results.html';
});

